import AppContextProvider from "@/components/AppContext"
import "./globals.css"
import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "社内管理システム",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body>
                <AppContextProvider>{children}</AppContextProvider>
            </body>
        </html>
    )
}
